name: Release Builds

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Setup EAS
        uses: expo/expo-github-action@v9
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        
      - name: Build Android Profile
        run: eas build --platform android --profile production --non-interactive
        
      - name: Build iOS Profile
        run: eas build --platform ios --profile production --non-interactive
